// import Head from "next/head";
// import Image from "next/image";
// import { Inter } from "next/font/google";
// import styles from "@/styles/Home.module.css";
// import Secone from "@/components/home/Secone";
// const inter = Inter({ subsets: ["latin"] });

// export default function Home() {
//   return (
//     <>
//       <Head>
//         <title>Goldsbet</title>
//         <meta name="description" content="Generated by TrucoGold" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
       
//       </Head>
//       <Secone />
//     </>
//   );
// }
import Head from "next/head";
import Secone from "@/components/home/Secone";

export default function Home() {
  return (
    <>
      <Head>
        <title>Goldsbet</title>
        <meta name="description" content="Generated by TrucoGold" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        {/* Meta Pixel Code */}
        <script
          dangerouslySetInnerHTML={{
            __html: `
              !function(f,b,e,v,n,t,s)
              {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
              n.callMethod.apply(n,arguments):n.queue.push(arguments)};
              if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
              n.queue=[];t=b.createElement(e);t.async=!0;
              t.src=v;s=b.getElementsByTagName(e)[0];
              s.parentNode.insertBefore(t,s)}(window, document,'script',
              'https://connect.facebook.net/en_US/fbevents.js');
              fbq('init', '720583070117721');
              fbq('track', 'PageView');
            `,
          }}
        />
        {/* End Meta Pixel Code */}
        <noscript>
          <img
            height="1"
            width="1"
            style={{ display: "none" }}
            src="https://www.facebook.com/tr?id=720583070117721&ev=PageView&noscript=1"
          />
        </noscript>
      </Head>
      <Secone />
    </>
  );
}

